name: Ejecutar CxC diario

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        run: python cxc.py
        env:
          ALEGRA_EMAIL: ${{ secrets.ALEGRA_EMAIL }}
          ALEGRA_TOKEN: ${{ secrets.ALEGRA_TOKEN }}

      - name: Subir CSV actualizado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cxc_Cuentasporcobrar.csv
          git commit -m "Actualización automática" || echo "No changes"
          git push
